version: '3'

services:
  nginx:
    restart: always
    image: nginx:1.18-alpine
    environment:
      # DEBUG: "true"
      # AUTH_URL: https://gitlab.example.com/jwt/auth?service=container_registry
      DISABLE_AUTH: "true"
      S3_SSL_DISABLE: "true"
      S3_BUCKET: mybackspace
      S3_ENDPOINT: minio.loc:9000
      S3_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      S3_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - ./njs:/etc/nginx/njs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    networks:
      s3_net:
  minio:
    restart: always
    image: minio/minio:RELEASE.2020-08-18T19-41-00Z
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_DOMAIN: minio.loc
    ports:
      - 9000:9000
    volumes:
      - ./minio_data:/data
      # - ./mc:/bin/mc
    command: server /data
    networks:
      s3_net:
        aliases:
          - minio.loc
          - mybackspace.minio.loc

networks:
  s3_net:
