{{- if or .Values.environments }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "njs-pypi.fullname" . }}
  labels:
    {{- include "njs-pypi.labels" . | nindent 4 }}
data:
{{ toYaml .Values.environments | indent 2 }}
{{- end }}
