{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "njs-pypi.fullname" . }}
  labels:
    {{- include "njs-pypi.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
